gazebo_ros_control:
  pid_gains:
    wheel_1_joint: {p: 100.0, i: 0.01, d: 10.0}
    wheel_2_joint: {p: 100.0, i: 0.01, d: 10.0}
    wheel_3_joint: {p: 100.0, i: 0.01, d: 10.0}
    wheel_4_joint: {p: 100.0, i: 0.01, d: 10.0}