version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ..:/root/robocock
      - ./.bashrc:/root/.bashrc
      - /root/catkin_ws/.catkin_tools
      - /root/catkin_ws/build
      - /root/catkin_ws/devel
      - /root/catkin_ws/install
      - /root/catkin_ws/logs
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
      - '$HOME/.Xauthority:/root/.Xauthority:rw'
      - /root/.dev
      - /root/.bash_history
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/dri
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - HOST_OS=linux
    # Keep alive entrypoint
    entrypoint: tail -f /dev/null