TrajectoryPlannerROS:
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_theta: 0.5
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 0.3
  min_vel_theta: -0.3
  min_in_place_vel_theta: 0.05
  backup_vel: -0.1
  escape_vel: -0.1
  # holonomic_robot: true
  