TrajectoryPlannerROS:
  acc_lim_x: 2
  acc_lim_y: 2
  acc_lim_theta: 2
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 0.6
  min_vel_theta: -0.6
  min_in_place_vel_theta: 0.05
  backup_vel: -0.1
  escape_vel: -0.1
  holonomic_robot: true
  